name: Initial
on:
  push:
    branch:
      - 'release'
jobs:
  checkout:
    name: Checkout
    uses: actions/checkout@v4.1.0
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Configure
      - run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
      - run: cmake --build build
      - run: cpack -G ZIP --config build/CPackConfig.cmake
      - run: zip --show-files build/Packages/*.zip
