name: Initial
on:
  push:
    branch:
      - release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: Pack
        run: cpack -G ZIP --config build/CPackConfig.cmake
      - name: Verify
        run: zip --show-files build/Packages/*.zip
