name: Initial
on:
  push:
    branches:
      - main
      - release
jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: Pack
        run: cpack -G 'ZIP;RPM;DEB' --config build/CPackConfig.cmake
