name: Deploy
on:
  push:
    tags:
      - v*
    branches:
      - main
      - release
jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: Zip Package
        run: cpack -G ZIP --config build/CPackConfig.cmake
      - name: Debian Package
        run: cpack -G DEB --config build/CPackConfig.cmake
      - name: RPM Package
        run: cpack -G RPM --config build/CPackConfig.cmake
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.refname }}
          release_name: "Release ${{ github.refname }}"
          body: "Release notes for ${{ github.refname }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #      -name: Upload Assets
        #        uses: actions/upload-release-asset@v1
        #        with:
        #          upload_url: ${{ steps.create_release.outputs.upload_url }}
        #          asset_path: ./Sample-*-Linux.zip
        #          asset_name: Sample.zip
