name: Deploy
permissions:
  contents: write
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: Zip Package
        run: cpack -G ZIP --config build/CPackConfig.cmake
      - name: Debian Package
        run: cpack -G DEB --config build/CPackConfig.cmake
      - name: RPM Package
        run: cpack -G RPM --config build/CPackConfig.cmake
      - name: Verify Package Content
        run: zip --show-files build/Packages/*.zip
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Release notes for ${{ github.ref_name }}"
          draft: false
          prerelease: false
      - name: Upload ZIP Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: build/Packages/Sample.zip
          asset_name: Sample.zip
          asset_content_type: application/zip
      - name: Upload DEB Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: build/Packages/Sample.deb
          asset_name: Sample.deb
          asset_content_type: application/deb
      - name: Upload RPM Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: build/Packages/Sample.rpm
          asset_name: Sample.rpm
          asset_content_type: application/rpm
